
rag_search_space:
  rewriter:
    model_url: ["http://localhost:9000/v1"]
    prompt_template_id: ["1", "2", "3"]

  chunking:
    chunk_size: [2048]
    chunk_overlap: [0]

  retrieve:
    model_url: ["models/all-MiniLM-L6-v2"]
    topk: [1, 3]
    bm25_weight: [0.0, 0.25, 0.5]

  reranker:
    model_url: ["models/ms-marco-MiniLM-L6-v2"]
    topk: [1, 3]

  pruner:
    model_url: ["http://localhost:9000/v1"]
    prompt_template_id: ["1", "2"]

  generator:
    model_url: ["http://localhost:9000/v1"]

eval_metrics:
  enabled: "F1,ROUGE-L,BLEU,METEOR,LLMAAJ"
  llmaaj:
    model_url: "http://localhost:9000/v1"
